---
title: "Explore"
author: "Adam Kiehl"
date: "11/22/21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dlookr)
library(tree)
```

Import data from local .csv
```{r, warning=FALSE}
fileName <- './Data/masterDF[2018-2020].csv'
data <- read_csv(fileName) %>%
  select(-'...1')
diagnose(data)
```

Assign point weights to seleced basic fantasy variables
```{r}
weights <- data.frame(stat = c('PassYds', 'PassTD', 'PassInt', 'RushYds', 'RushTD', 'Rec', 'RecYds', 'RecTD', 'FL'),
                      pts = c(.04, 4, -1, .1, 6, 1, .1, 6, -2))
```

Add field for single-game fantasy points based on weights
```{r}
data <- data %>% mutate(fanPts = as.vector(as.matrix(data[, weights$stat]) %*% weights$pts))
```

Fit a naive tree to predict `fanPts`
```{r}
model <- tree(fanPts ~ ., data = data[, c(4:23, 63)])
summary(model)
```

```{r}
plot(model)
text(model)
```

Linear regression returns the weights of each variable since `fanPts` is a linear combination of predictors
```{r}
model <- lm(fanPts ~ PassYds + PassTD + PassInt + RushYds + RushTD + Rec + RecYds + RecTD + FL, data = data[, c(4:23, 63)])
summary(model)
```

Write modified .csv to local data frame
```{r}
data %>% write_csv(fileName)
```

